/*
 * This file was generated by a tool.
 * Rerun sql-ts to regenerate this file.
 */
export interface cc_cedict {
  id?: string;
  simplified: string;
  traditional: string;
  pinyin: string;
  definitions: string[];
}
export interface cc_cedict_definition {
  cc_cedict_id: string;
  definition_meaning: string;
}
export interface corpus {
  title: string;
  licence: string;
  website: string;
  summary: string;
}
export interface document {
  id?: string;
  sub_corpus_title: string;
  corpus_title: string;
  previous_document: string | null;
  english: string | null;
  chinese: string;
  words_upos_not_punct: any;
}
export interface document_augmented {
  document_id: string | null;
  document_chinese: string | null;
  document_english: string | null;
  unique_words_no_punct: any | null;
  unique_words_no_num_no_punct: any | null;
}
export interface document_with_words {
  document_id: string | null;
  document_chinese: string | null;
  document_english: string | null;
  words: any | null;
}
export interface document_word {
  document_id: string | null;
  word: string | null;
}
export interface listen_log {
  date_time: Date;
  student_id: string;
  understood: boolean;
  sentence_word_id: number;
  sentence_id: string;
}
export interface named_entity {
  id?: string;
  chinese: string;
  entity_type: string;
  start_char: number;
  end_char: number;
  document_id: string;
}
export interface read_log {
  date_time: Date;
  student_id: string;
  understood: boolean;
  sentence_word_id: number;
  sentence_id: string;
}
export interface sentence {
  id?: string;
  document_id: string;
  chinese: string;
  sentiment: string;
}
export interface sentence_word {
  id: number;
  sentence_id: string;
  word_hanzi: string;
  lemma: string;
  part_of_speech: string;
  universal_part_of_speech: string;
  head: number;
  deprel: string;
  feats: any;
  start_char: number;
  end_char: number;
  ner: string;
  named_entity_id: string | null;
}
export interface student {
  id?: string;
  first_name: string;
  last_name: string;
}
export interface student_document_listen {
  student_id: string;
  document_id: string;
  listen_count: string;
}
export interface student_document_read {
  student_id: string;
  document_id: string;
  read_count: string;
}
export interface student_word_listen {
  student_id: string;
  word_hanzi: string;
  f1: string;
  f2: string;
  due: Date;
  previous: Date;
  understood_count: string;
  understood_distinct_documents_count: string;
}
export interface student_word_read {
  student_id: string;
  word_hanzi: string;
  f1: string;
  f2: string;
  due: Date;
  previous: Date;
  understood_count: string;
  understood_distinct_documents_count: string;
}
export interface sub_corpus {
  title: string;
  corpus_title: string;
  summary: string;
}
export interface word {
  hanzi: string;
  hsk_word_2010: number;
  hsk_char_2010: number;
}
